services:
    backend:
        build: ../backend
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant-db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
        restart: unless-stopped

    frontend:
        build: ../frontend
        ports:
            - "5173:5173"
        restart: unless-stopped

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: restaurant-db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    postgres_data:
